version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql

  spring:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
    volumes:
      - files:/files
      - logs:/logs

  svelte:
    build: ./board
    ports:
      - "80:80"
    restart: always
    depends_on:
      - spring

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    restart: always
    environment:
      DATA_SOURCE_NAME: root:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

volumes:
    db-data:
    prometheus-data:
    files:
    logs: