name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 jobs:
   build:
     runs-on: ubuntu-latest
     services:
       mysql:
         image: mysql:5.7
         ports:
           - 3306:3306
         env:
           MYSQL_ROOT_PASSWORD: password
           MYSQL_DATABASE: project_test
     env:
       SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/project_test
       SPRING_DATASOURCE_PASSWORD: password
     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
         
     - name: Build with Maven
       run: mvn -B package --file pom.xml
